name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
     - name: Deploy to EC2
       uses: appleboy/ssh-action@master
       env:
         SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
         REMOTE_HOST: ${{ secrets.HOST_DNS }}
         REMOTE_USER: ${{ secrets.USERNAME }}
         script: |
            docker stop newlab4image || true
            docker rm newlab4image || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/newlab4image:${{ github.sha }}
            docker run -d --name webapp -p 80:80 ${{ secrets.DOCKER_USERNAME }}/newlab4image:${{ github.sha }}
